name:                     Agent 与火山 MCP Server
name_en:                  MCP
description:              展示如何通过 mcp_router 调用 MCP 工具集。
details:                  这是一个通过内置的 mcp_router 工具集成和调度 MCP 工具集Agent。
tags:
  # 行业场景标签（金融、汽车、泛互、医疗、零售、广告营销、能源电力、信息技术服务、教育、工业、制造等）
  industry:      教育        
  from:                   volcengine 
  framework:              veadk
  language:               python
  tech:                   
    - MCPToolset
    - veadk
    - mcp
type:                     tutorial 
senarios:                 # 应用场景（2-6个），type 为 application 时必填
  - name:                 # 应用场景名称（2-15字）
    desc:                 # 应用场景描述（10-20字）
  - name:
    desc:
prompts:                  # Prompt 样例
  - text:                 一只青蛙一次可以跳 1 级台阶，也可以跳 2 级。它要跳上一个 10 级台阶，总共有多少种跳法？如果是 n 级呢？
    resource_url:         # 必要的多模态数据 URL（公网可访问）
envs:                     # 所需的环境变量（用于第三方依赖服务）
  - name:                 火山引擎访问密钥
    key:                  VOLCENGINE_ACCESS_KEY
    url:                  https://www.volcengine.com/docs/6291/65568?lang=zh
  - name:                 火山引擎访问密钥
    key:                  VOLCENGINE_SECRET_KEY
    url:                  https://www.volcengine.com/docs/6291/65568?lang=zh
  - name:                 火山MCP工具集地址
    key:                  TOOL_MCP_ROUTER_URL
    url:                  https://www.volcengine.com/docs/86681/1844858?lang=zh
  - name:                 火山MCP工具集访问凭证
    key:                  TOOL_MCP_ROUTER_API_KEY
    url:                  https://www.volcengine.com/docs/86681/1844858?lang=zh
components:               # Agentkit 依赖服务
  - type: mcp_toolset              # 服务类型，可选项为 tool | knowledgebase | memory
    # 对应产品（不区分大小写）
    # knowledgebase: VikingKnowledge
    # memory: VikingMem | Mem0
    product: mcp_toolset
models:                   # 涉及到的具体模型列表
    - doubao-seed-1-8-251228

image: agentkit-platform-2113735418-cn-beijing.cr.volces.com/agentkit/mcp_simple:v1.0.0