[project]
name = "vikingdb"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "google-adk==1.36.1",
    "veadk-python==1.0.9",
    "veadk-python[extensions]==1.0.9",
    "agentkit-sdk-python>=0.8.0",
    "python-dotenv>=1.0.0",
    "litellm"
]
